import Head from 'next/head'
// import Image from 'next/image'
import styles from '../styles/Home.module.css'

// test
export async function getStaticProps() {
  // {
  //   "data": {
  //     "repository": {
  //       "issue": {
  //         "reactionGroups": [
  //           { "content": "THUMBS_UP", "users": { "totalCount": 0 } },
  //           { "content": "THUMBS_DOWN", "users": { "totalCount": 0 } },
  //           { "content": "LAUGH", "users": { "totalCount": 0 } },
  //           { "content": "HOORAY", "users": { "totalCount": 0 } },
  //           { "content": "CONFUSED", "users": { "totalCount": 0 } },
  //           { "content": "HEART", "users": { "totalCount": 0 } },
  //           { "content": "ROCKET", "users": { "totalCount": 0 } },
  //           { "content": "EYES", "users": { "totalCount": 0 } }
  //         ]
  //       }
  //     }
  //   }
  // }
  console.log("TOKEN IS ", process.env.GITHUB_TOKEN)
  const res = await fetch('https://api.github.com/graphql', {
    method: 'POST',
    headers: {
      Authorization: `bearer ${process.env.GITHUB_TOKEN}`
    },
    body: JSON.stringify({
      query: `query {
        repository(owner:"aws-amplify", name:"amplify-console") {
          issue(number:1860) {
            reactionGroups {
              content
              users(first: 0) {
                totalCount
              }
            }
          }
        }
      }`
    })
  })

  const json = await res.json()
  if (res.status !== 200) {
    console.error(json)
    if (!process.env.secrets.GITHUB_TOKEN) {
      console.log('token is empty')
    }
    throw new Error('Failed to fetch API')
  }

  // [0, 0, 0, 0, 0, 0, 0, 0]
  const reactions = json.data.repository.issue.reactionGroups.map(
    (item) => item.users.totalCount
  )

  return {
    props: {
      reactions
    },
    revalidate: 1
  }
}

export default function Home({reactions}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App - SSG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js! (static)</a>
        </h1>

        <div className='line'>
          <span className='emoji'>👍</span> <strong>{reactions[0]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>👎</span> <strong>{reactions[1]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>😄</span> <strong>{reactions[2]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>🎉</span> <strong>{reactions[3]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>😕</span> <strong>{reactions[4]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>🧡</span> <strong>{reactions[5]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>🚀</span> <strong>{reactions[6]}</strong>
        </div>
        <div className='line'>
          <span className='emoji'>👀</span> <strong>{reactions[7]}</strong>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            {/* <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} /> */}
          </span>
        </a>
      </footer>
    </div>
  )
}
